/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vietngan_bds.GUI;

import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vietngan_bds.DataAccessLayer.db;

/**
 *
 * @author quocdunginfo
 */
public class F_CHECK extends javax.swing.JFrame {

    /**
     * Creates new form F_CHECK
     */
    public F_CHECK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kiểm tra kết nối tới CSDL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Đang kiểm tra kết nối tới CSDL! Vui Lòng chờ trong giây lát...");

        jProgressBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jProgressBar.setValue(23);
        jProgressBar.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //0: Trạng thái ban đầu, 1: OK, -1: ERROR
    int database_state=0;
    Thread progress=null, test=null;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        progress=new Thread(){
            @Override
            public void run()
            {
                int i=0;
                while(i<=100){
                    if(database_state==-1 || database_state==1)
                    {
                        jProgressBar.setValue(100);
                        progress.interrupt();
                        break;
                    }
                    jProgressBar.setValue(i);
                    i++;
                    try {
                        progress.sleep(50);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(F_CHECK.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                progress.interrupted();
            }
        };
        progress.start();
        
        test =new Thread()
        {
            public void run() {
                
                if(db.getCon()==null)
                {
                    //ERROR
                    database_state=-1;
                    int opt = JOptionPane.showConfirmDialog(null, "Không tìm thấy CSDL khả dụng hoặc\n"
                            + "cấu hình hệ thống chưa đúng!\n"
                            + "Chọn OK để cấu hình hệ thống ngay");
                    if(opt==JOptionPane.OK_OPTION)
                    {
                        F_CONFIG config=new F_CONFIG(true);
                        config.setVisible(true);
                        //đã cấu hình xong
                        //restart lại hệ thống
                        F_CHECK newch=new F_CHECK();
                        newch.setVisible(true);
                        dispose();
                    }
                    test.interrupt();
                }
                else
                {
                    database_state=1;
                    test.interrupt();
                    setVisible(false);
                    F_LOGIN login=new F_LOGIN();
                    login.setVisible(true);
                }
            }
        };
        test.start();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_CHECK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_CHECK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_CHECK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_CHECK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_CHECK().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
}
