/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vietngan_bds.GUI;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import vietngan_bds.DataTranferObject.DTO_USER;
import vietngan_bds.Utilities.Debug;
import vietngan_bds.Utilities.Global;

/**
 *
 * @author quocdunginfo
 */
public class F_MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form F_MainFrame
     */
    public F_MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_qlyttbds = new javax.swing.JButton();
        jButton_qlyuser = new javax.swing.JButton();
        jButton_config = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Bảng chức năng");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jButton_qlyttbds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vietngan_bds/Icon/house.png"))); // NOI18N
        jButton_qlyttbds.setText("Quản lý thông tin Bất động sản (F2)");
        jButton_qlyttbds.setFocusable(false);
        jButton_qlyttbds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_qlyttbdsActionPerformed(evt);
            }
        });
        jButton_qlyttbds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_qlyttbdsKeyPressed(evt);
            }
        });

        jButton_qlyuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vietngan_bds/Icon/user-group-icon.png"))); // NOI18N
        jButton_qlyuser.setText("Quản lý thông tin Nhân viên (F3)");
        jButton_qlyuser.setFocusable(false);
        jButton_qlyuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_qlyuserActionPerformed(evt);
            }
        });

        jButton_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vietngan_bds/Icon/config.png"))); // NOI18N
        jButton_config.setText("Cấu hình Hệ thống (F4)");
        jButton_config.setFocusable(false);
        jButton_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_configActionPerformed(evt);
            }
        });

        jButton_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vietngan_bds/Icon/logout-icon.png"))); // NOI18N
        jButton_logout.setText("Đăng xuất (ESC)");
        jButton_logout.setFocusable(false);
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_qlyttbds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_config, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_qlyuser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_qlyttbds, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_qlyuser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_config, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_qlyuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_qlyuserActionPerformed
        // TODO add your handling code here:
        F_QLYUSER vd=new F_QLYUSER();
        vd.setVisible(true);
    }//GEN-LAST:event_jButton_qlyuserActionPerformed

    private void jButton_qlyttbdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_qlyttbdsActionPerformed
        // TODO add your handling code here:
        F_QLY_TTBDS vd=new F_QLY_TTBDS();
        vd.setVisible(true);
    }//GEN-LAST:event_jButton_qlyttbdsActionPerformed

    private void jButton_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_configActionPerformed
        // TODO add your handling code here:
        F_CONFIG vd=new F_CONFIG(true);
        vd.setVisible(true);
        //restart app
        F_CHECK newch=new F_CHECK();
        newch.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_configActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //phân quyền hệ thống
        jButton_config.setEnabled(Global.user._RoleName().equals("admin"));
        
        jPanel1.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:
        //del session
        Global.user = new DTO_USER();
        
        //Mở login lên
        F_LOGIN vd=new F_LOGIN();
        vd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int opt=JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thoát khỏi phần mềm!");
        if(opt==JOptionPane.YES_OPTION)
        {
            //không thoát
            System.exit(1);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton_qlyttbdsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_qlyttbdsKeyPressed
        
    }//GEN-LAST:event_jButton_qlyttbdsKeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
        Debug.WriteLine(evt.getKeyCode());
        switch(evt.getKeyCode())
        {
            case KeyEvent.VK_F2:
                jButton_qlyttbds.doClick();
                break;
            case KeyEvent.VK_F3:
                jButton_qlyuser.doClick();
                break;
            case KeyEvent.VK_F4:
                jButton_config.doClick();
                break;
            case KeyEvent.VK_ESCAPE:
                jButton_logout.doClick();
                break;
            default:break;
        }
    }//GEN-LAST:event_jPanel1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_config;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_qlyttbds;
    private javax.swing.JButton jButton_qlyuser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
