/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vietngan_bds.GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import vietngan_bds.BusinessLogicLayer.BLL_DIACHI;
import vietngan_bds.BusinessLogicLayer.BLL_DONVI;
import vietngan_bds.BusinessLogicLayer.BLL_DTNXD;
import vietngan_bds.BusinessLogicLayer.BLL_GIAGD;
import vietngan_bds.BusinessLogicLayer.BLL_HIENTRANG;
import vietngan_bds.BusinessLogicLayer.BLL_HUONG;
import vietngan_bds.BusinessLogicLayer.BLL_LOAIBDS;
import vietngan_bds.BusinessLogicLayer.BLL_TIENTE;
import vietngan_bds.BusinessLogicLayer.BLL_TTBDS;
import vietngan_bds.BusinessLogicLayer.BLL_TTGD;
import vietngan_bds.BusinessLogicLayer.BLL_USER;
import vietngan_bds.BusinessLogicLayer.BLL_VITRI;
import vietngan_bds.DataTranferObject.DTO_DIACHI;
import vietngan_bds.DataTranferObject.DTO_DONVI;
import vietngan_bds.DataTranferObject.DTO_HUONG;
import vietngan_bds.DataTranferObject.DTO_TIENTE;
import vietngan_bds.DataTranferObject.DTO_TTBDS;
import vietngan_bds.DataTranferObject.DTO_USER;
import vietngan_bds.DataTranferObject.DTO_VITRI;
import vietngan_bds.Utilities.Debug;
import vietngan_bds.Utilities.UTL_ComboBox;
import vietngan_bds.Utilities.UTL_Date;
import vietngan_bds.Utilities.UTL_String;
import vietngan_bds.Utilities.UTL_Table;
import vietngan_bds.Utilities.UTL_TextField;

/**
 *
 * @author quocdunginfo
 */
public class F_QLY_TTBDS extends javax.swing.JFrame {
    private DTO_DIACHI obj_vitri_diachi = new DTO_DIACHI();
    /**
     * Creates new form F_QLY_TTBDS
     */
    public F_QLY_TTBDS() {
        initComponents();
    }
    private void Load_pre_value()
    {
        //HUONG
        jComboBox_vt_huong.removeAllItems();
        //load combobox huong
        UTL_ComboBox.AddComboBoxItem(jComboBox_vt_huong, -1, "(Bất kỳ)");
        ArrayList<DTO_HUONG> list = new BLL_HUONG().TimKiem(-1, "");
        for(DTO_HUONG tmp:list)
        {
            UTL_ComboBox.AddComboBoxItem(jComboBox_vt_huong, tmp.id, tmp.huong);
        }
        jComboBox_vt_huong.setSelectedIndex(0);
        
        //TIENTE 1 và 2
        jComboBox_giagd_ban_tiente.removeAllItems();
        jComboBox_giagd_thue_tiente.removeAllItems();
        //load combobox tiente
        ArrayList<DTO_TIENTE> list2 = new BLL_TIENTE().TimKiem(-1, "");
        for(DTO_TIENTE tmp:list2)
        {
            UTL_ComboBox.AddComboBoxItem(jComboBox_giagd_ban_tiente, tmp.id, tmp.name);
            UTL_ComboBox.AddComboBoxItem(jComboBox_giagd_thue_tiente, tmp.id, tmp.name);
        }
        jComboBox_giagd_ban_tiente.setSelectedIndex(0);
        jComboBox_giagd_thue_tiente.setSelectedIndex(0);
        
        //DONVI 1 và 2
        jComboBox_giagd_ban_donvi.removeAllItems();
        jComboBox_giagd_thue_donvi.removeAllItems();
        //load combobox tiente
        ArrayList<DTO_DONVI> list3 = new BLL_DONVI().TimKiem(-1, "");
        for(DTO_DONVI tmp:list3)
        {
            UTL_ComboBox.AddComboBoxItem(jComboBox_giagd_ban_donvi, tmp.id, tmp.name);
            UTL_ComboBox.AddComboBoxItem(jComboBox_giagd_thue_donvi, tmp.id, tmp.name);
        }
        jComboBox_giagd_ban_donvi.setSelectedIndex(0);
        jComboBox_giagd_thue_donvi.setSelectedIndex(0);
        //NHANVIEN
        //load combobox nhanvien
        jComboBox_nhanvien.removeAllItems();
        UTL_ComboBox.AddComboBoxItem(jComboBox_nhanvien, -1, "(Bất kỳ)");
        ArrayList<DTO_USER> list4 = new BLL_USER().TimKiem(-1, "", "", -1, -1);
        for(DTO_USER tmp:list4)
        {
            UTL_ComboBox.AddComboBoxItem(jComboBox_nhanvien, tmp.id, tmp.username+" ("+ tmp.fullname+")");
            
        }
        jComboBox_nhanvien.setSelectedIndex(0);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser_ngayfrom = new com.toedter.calendar.JDateChooser();
        jDateChooser_ngayto = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_nhanvien = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox_ttgd_ban = new javax.swing.JCheckBox();
        jCheckBox_ttgd_chothue = new javax.swing.JCheckBox();
        jCheckBox_ttgd_sangnhuong = new javax.swing.JCheckBox();
        jCheckBox_ttgd_timthue = new javax.swing.JCheckBox();
        jCheckBox_ttgd_timmua = new javax.swing.JCheckBox();
        jCheckBox_ttgd_timsang = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox_lbds_nhapho = new javax.swing.JCheckBox();
        jCheckBox_lbds_bietthu = new javax.swing.JCheckBox();
        jCheckBox_lbds_canhochungcu = new javax.swing.JCheckBox();
        jCheckBox_lbds_caoocvanphong = new javax.swing.JCheckBox();
        jCheckBox_lbds_matbang = new javax.swing.JCheckBox();
        jCheckBox_lbds_dat = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jTextField_lbds_khac = new javax.swing.JTextField();
        jTabbedPane_giagd = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jTextField_giagd_ban = new javax.swing.JTextField();
        jComboBox_giagd_ban_tiente = new javax.swing.JComboBox();
        jLabel48 = new javax.swing.JLabel();
        jComboBox_giagd_ban_donvi = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField_giagd_ban1 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jTextField_giagd_thue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_giagd_thue1 = new javax.swing.JTextField();
        jComboBox_giagd_thue_tiente = new javax.swing.JComboBox();
        jComboBox_giagd_thue_donvi = new javax.swing.JComboBox();
        jLabel51 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jTextField_vt_diachi = new javax.swing.JTextField();
        jButton_vt_chondc = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox_vt_huong = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField_dtnxd_chieungang = new javax.swing.JTextField();
        jTextField_dtnxd_chieudai = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField_dtnxd_dtkv = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_dtnxd_dtxd = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField_dtnxd_dtsd = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField_dtnxd_dtsan = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_dtnxd_chieungang1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_dtnxd_chieudai1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_dtnxd_dtkv1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_dtnxd_dtxd1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_dtnxd_dtsd1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_dtnxd_dtsan1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser_dtnxd_nxd = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jDateChooser_dtnxd_nxd1 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_ht_solau = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_ht_solau1 = new javax.swing.JTextField();
        jTextField_ht_gac = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_ht_gac1 = new javax.swing.JTextField();
        jButton_TimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_kq = new javax.swing.JTable();
        jButton_xemchitiet = new javax.swing.JButton();
        jButton_sua = new javax.swing.JButton();
        jButton_xoa = new javax.swing.JButton();
        jButton_them = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý thông tin bất động sản");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin tìm kiếm"), "Thông tin tìm kiếm"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin cơ bản"));

        jLabel1.setText("Mã phiếu:");

        jLabel2.setText("Ngày lập từ:");

        jDateChooser_ngayfrom.setDateFormatString("dd/MM/yyyy");

        jDateChooser_ngayto.setDateFormatString("dd/MM/yyyy");

        jLabel3.setText("đến");

        jLabel4.setText("Nhân viên GD:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jDateChooser_ngayfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_ngayto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_nhanvien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_ngayfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser_ngayto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin giao dịch"));
        jPanel3.setToolTipText("");
        jPanel3.setName(""); // NOI18N

        jCheckBox_ttgd_ban.setText("Bán");
        jCheckBox_ttgd_ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ttgd_banActionPerformed(evt);
            }
        });

        jCheckBox_ttgd_chothue.setText("Cho thuê");

        jCheckBox_ttgd_sangnhuong.setText("Sang nhượng");

        jCheckBox_ttgd_timthue.setText("Tìm thuê");
        jCheckBox_ttgd_timthue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ttgd_timthueActionPerformed(evt);
            }
        });

        jCheckBox_ttgd_timmua.setText("Tìm mua");
        jCheckBox_ttgd_timmua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ttgd_timmuaActionPerformed(evt);
            }
        });

        jCheckBox_ttgd_timsang.setText("Tìm sang");
        jCheckBox_ttgd_timsang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ttgd_timsangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_ttgd_ban)
                    .addComponent(jCheckBox_ttgd_timmua))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_ttgd_chothue)
                    .addComponent(jCheckBox_ttgd_timthue))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_ttgd_sangnhuong)
                    .addComponent(jCheckBox_ttgd_timsang)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_ttgd_ban)
                    .addComponent(jCheckBox_ttgd_chothue)
                    .addComponent(jCheckBox_ttgd_sangnhuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_ttgd_timmua)
                    .addComponent(jCheckBox_ttgd_timthue)
                    .addComponent(jCheckBox_ttgd_timsang)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Loại bất động sản"));
        jPanel7.setToolTipText("");
        jPanel7.setName(""); // NOI18N

        jCheckBox_lbds_nhapho.setText("Nhà phố");
        jCheckBox_lbds_nhapho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_lbds_nhaphoActionPerformed(evt);
            }
        });

        jCheckBox_lbds_bietthu.setText("Biệt thự");
        jCheckBox_lbds_bietthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_lbds_bietthuActionPerformed(evt);
            }
        });

        jCheckBox_lbds_canhochungcu.setText("Căn hộ chung cư");
        jCheckBox_lbds_canhochungcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_lbds_canhochungcuActionPerformed(evt);
            }
        });

        jCheckBox_lbds_caoocvanphong.setText("Cao ốc văn phòng");
        jCheckBox_lbds_caoocvanphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_lbds_caoocvanphongActionPerformed(evt);
            }
        });

        jCheckBox_lbds_matbang.setText("Mặt bằng");
        jCheckBox_lbds_matbang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_lbds_matbangActionPerformed(evt);
            }
        });

        jCheckBox_lbds_dat.setText("Đất");
        jCheckBox_lbds_dat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_lbds_datActionPerformed(evt);
            }
        });

        jLabel23.setText("Khác:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_lbds_dat)
                            .addComponent(jCheckBox_lbds_nhapho)
                            .addComponent(jCheckBox_lbds_bietthu)
                            .addComponent(jCheckBox_lbds_canhochungcu)
                            .addComponent(jCheckBox_lbds_caoocvanphong)
                            .addComponent(jCheckBox_lbds_matbang))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_lbds_khac))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jCheckBox_lbds_nhapho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_lbds_bietthu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_lbds_canhochungcu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_lbds_caoocvanphong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_lbds_matbang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_lbds_dat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField_lbds_khac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel46.setText("Giá từ:");

        jLabel48.setText("/");

        jLabel5.setText("đến");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_giagd_ban, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_giagd_ban1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_giagd_ban_tiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_giagd_ban_donvi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jTextField_giagd_ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_giagd_ban_tiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(jComboBox_giagd_ban_donvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_giagd_ban1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane_giagd.addTab("   Giá bán   ", jPanel12);

        jLabel47.setText("Giá từ:");

        jLabel6.setText("đến");

        jLabel51.setText("/");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_giagd_thue, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_giagd_thue1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_giagd_thue_tiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_giagd_thue_donvi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jTextField_giagd_thue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_giagd_thue_tiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(jComboBox_giagd_thue_donvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_giagd_thue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane_giagd.addTab("   Giá thuê   ", jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Địa chỉ BDS"));

        jLabel44.setText("Địa chỉ:");

        jButton_vt_chondc.setText("Chọn");
        jButton_vt_chondc.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_vt_chondc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vt_chondcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_vt_diachi, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_vt_chondc))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel44)
                .addComponent(jTextField_vt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton_vt_chondc))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Vị trí"));
        jPanel6.setToolTipText("");
        jPanel6.setName(""); // NOI18N

        jLabel22.setText("Hướng:");

        jComboBox_vt_huong.setMaximumRowCount(10);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(30, 30, 30)
                .addComponent(jComboBox_vt_huong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel22)
                .addComponent(jComboBox_vt_huong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Diện tích và năm xây dựng"));
        jPanel8.setToolTipText("");
        jPanel8.setName(""); // NOI18N

        jLabel24.setText("Chiều ngang:");

        jTextField_dtnxd_chieudai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dtnxd_chieudaiActionPerformed(evt);
            }
        });

        jLabel25.setText("Chiều dài:");

        jLabel26.setText("DTKV:");

        jLabel27.setText("DTXD:");

        jLabel28.setText("DTSD:");

        jLabel29.setText("DT sân:");

        jLabel7.setText("đến");

        jLabel8.setText("đến");

        jLabel9.setText("đến");

        jLabel10.setText("đến");

        jLabel11.setText("đến");

        jLabel12.setText("đến");

        jLabel17.setText("Năm XD:");

        jDateChooser_dtnxd_nxd.setDateFormatString("MM/yyyy");

        jLabel18.setText("đến");

        jDateChooser_dtnxd_nxd1.setDateFormatString("MM/yyyy");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_dtnxd_chieungang, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_dtnxd_chieungang1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser_dtnxd_nxd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel25))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_dtnxd_dtsan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(jTextField_dtnxd_dtsd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_dtnxd_dtxd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_dtnxd_dtkv, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_dtnxd_chieudai))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_dtnxd_nxd1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_dtnxd_chieudai1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_dtnxd_dtkv1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_dtnxd_dtxd1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_dtnxd_dtsd1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_dtnxd_dtsan1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField_dtnxd_chieungang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_dtnxd_chieungang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField_dtnxd_chieudai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_dtnxd_chieudai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField_dtnxd_dtkv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_dtnxd_dtkv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField_dtnxd_dtxd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_dtnxd_dtxd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField_dtnxd_dtsd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_dtnxd_dtsd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField_dtnxd_dtsan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_dtnxd_dtsan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_dtnxd_nxd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jDateChooser_dtnxd_nxd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Hiện trạng"));
        jPanel5.setToolTipText("");
        jPanel5.setName(""); // NOI18N

        jLabel13.setText("Số lầu:");

        jLabel14.setText("Gác:");

        jLabel15.setText("đến");

        jTextField_ht_gac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ht_gacActionPerformed(evt);
            }
        });

        jLabel16.setText("đến");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_ht_gac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ht_gac1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField_ht_solau, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ht_solau1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ht_solau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_ht_solau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ht_gac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_ht_gac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)))
        );

        jButton_TimKiem.setText("Tìm kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane_giagd, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane_giagd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jButton_TimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTable_kq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_kq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_kqMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_kq);

        jButton_xemchitiet.setText("Xem chi tiết");
        jButton_xemchitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xemchitietActionPerformed(evt);
            }
        });

        jButton_sua.setText("Sửa");
        jButton_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suaActionPerformed(evt);
            }
        });

        jButton_xoa.setText("Xóa");
        jButton_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xoaActionPerformed(evt);
            }
        });

        jButton_them.setText("Thêm");
        jButton_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_xemchitiet, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jButton_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_xemchitiet)
                        .addGap(4, 4, 4)
                        .addComponent(jButton_them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_sua)
                        .addGap(33, 33, 33)
                        .addComponent(jButton_xoa)
                        .addContainerGap())))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_ttgd_banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ttgd_banActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ttgd_banActionPerformed

    private void jCheckBox_ttgd_timthueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ttgd_timthueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ttgd_timthueActionPerformed

    private void jCheckBox_ttgd_timmuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ttgd_timmuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ttgd_timmuaActionPerformed

    private void jCheckBox_ttgd_timsangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ttgd_timsangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ttgd_timsangActionPerformed

    private void jCheckBox_lbds_nhaphoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_lbds_nhaphoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_lbds_nhaphoActionPerformed

    private void jCheckBox_lbds_bietthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_lbds_bietthuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_lbds_bietthuActionPerformed

    private void jCheckBox_lbds_canhochungcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_lbds_canhochungcuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_lbds_canhochungcuActionPerformed

    private void jCheckBox_lbds_caoocvanphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_lbds_caoocvanphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_lbds_caoocvanphongActionPerformed

    private void jCheckBox_lbds_matbangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_lbds_matbangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_lbds_matbangActionPerformed

    private void jCheckBox_lbds_datActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_lbds_datActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_lbds_datActionPerformed

    private void jButton_vt_chondcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vt_chondcActionPerformed
        F_DIACHI_PICKUP vd = new F_DIACHI_PICKUP(this, true, "sua", this.obj_vitri_diachi);
        vd.setVisible(true);
        //chọn xong
        //cập nhật obj_csh_diachi và textfield
        this.obj_vitri_diachi = vd.result;
        jTextField_vt_diachi.setText(this.obj_vitri_diachi._ToString());
    }//GEN-LAST:event_jButton_vt_chondcActionPerformed

    private void jTextField_dtnxd_chieudaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dtnxd_chieudaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dtnxd_chieudaiActionPerformed

    private void jTextField_ht_gacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ht_gacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ht_gacActionPerformed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        // TODO add your handling code here:
        ArrayList<Integer> re = new BLL_TTBDS().Get_All_Id();
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        //THONG TIN CO BAN
        if(!jTextField_id.getText().equals(""))
        {
            int id= UTL_TextField.GetInt(jTextField_id);
            re=new BLL_TTBDS().Filter_id(re, id);
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        if(jDateChooser_ngayfrom.getDate()!=null && jDateChooser_ngayto.getDate()!=null)
        {
            re=new BLL_TTBDS().Filter_ngay(re, jDateChooser_ngayfrom.getDate(), jDateChooser_ngayto.getDate());
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        if(UTL_ComboBox.GetComboBoxValueInt(jComboBox_nhanvien)>0)
        {
            re=new BLL_USER().Filter_id(re, UTL_ComboBox.GetComboBoxValueInt(jComboBox_nhanvien));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        //DIACHI
        if(!jTextField_vt_diachi.getText().equals(""))
        {
            re=new BLL_DIACHI().Filter_All(re, obj_vitri_diachi.fk_tinhthanh.id ,
                    obj_vitri_diachi.fk_quanhuyen.id, obj_vitri_diachi.fk_phuongxa.id,
                    obj_vitri_diachi.duong, obj_vitri_diachi.sonha);
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        //HUONG
        if(UTL_ComboBox.GetComboBoxValueInt(jComboBox_vt_huong)>0)
        {
            re=new BLL_HUONG().Filter_id(re, UTL_ComboBox.GetComboBoxValueInt(jComboBox_vt_huong));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        //GIAGD
        if(!jTextField_giagd_ban.getText().equals("") && !jTextField_giagd_ban1.getText().equals(""))
        {
            re=new BLL_GIAGD().Filter_giaban(re, UTL_TextField.GetDouble(jTextField_giagd_ban),
                    UTL_TextField.GetDouble(jTextField_giagd_ban1),
                    UTL_ComboBox.GetComboBoxValueInt(jComboBox_giagd_ban_tiente),
                    UTL_ComboBox.GetComboBoxValueInt(jComboBox_giagd_ban_donvi));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        if(!jTextField_giagd_thue.getText().equals("") && !jTextField_giagd_thue1.getText().equals(""))
        {
            re=new BLL_GIAGD().Filter_giathue(re, UTL_TextField.GetDouble(jTextField_giagd_thue),
                    UTL_TextField.GetDouble(jTextField_giagd_thue1),
                    UTL_ComboBox.GetComboBoxValueInt(jComboBox_giagd_thue_tiente),
                    UTL_ComboBox.GetComboBoxValueInt(jComboBox_giagd_thue_donvi));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        //LOAI_BDS
        re=new BLL_LOAIBDS().Filter_All(re,
                jCheckBox_lbds_nhapho.isSelected()==true?1:0,
                jCheckBox_lbds_bietthu.isSelected()==true?1:0,
                jCheckBox_lbds_canhochungcu.isSelected()==true?1:0,
                jCheckBox_lbds_caoocvanphong.isSelected()==true?1:0,
                jCheckBox_lbds_matbang.isSelected()==true?1:0,
                jCheckBox_lbds_dat.isSelected()==true?1:0,
                UTL_TextField.GetString(jTextField_lbds_khac));
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        //TTGD
        re=new BLL_TTGD().Filter_All(re,
                jCheckBox_ttgd_ban.isSelected()==true?1:0,
                jCheckBox_ttgd_chothue.isSelected()==true?1:0,
                jCheckBox_ttgd_sangnhuong.isSelected()==true?1:0,
                jCheckBox_ttgd_timmua.isSelected()==true?1:0,
                jCheckBox_ttgd_timthue.isSelected()==true?1:0,
                jCheckBox_ttgd_timsang.isSelected()==true?1:0,
                "");
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        //HIENTRANG
        if(!jTextField_ht_gac.getText().equals("") && !jTextField_ht_gac1.getText().equals(""))
        {
            re=new BLL_HIENTRANG().Filter_gac(re, UTL_TextField.GetDouble(jTextField_ht_gac),
                    UTL_TextField.GetDouble(jTextField_ht_gac1));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        if(!jTextField_ht_solau.getText().equals("") && !jTextField_ht_solau1.getText().equals(""))
        {
            re=new BLL_HIENTRANG().Filter_solau(re, UTL_TextField.GetDouble(jTextField_ht_solau),
                    UTL_TextField.GetDouble(jTextField_ht_solau1));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        //DTNXD
        if(!jTextField_dtnxd_chieungang.getText().equals("") && !jTextField_dtnxd_chieungang1.getText().equals(""))
        {
            re=new BLL_DTNXD().Filter_chieungang(re, UTL_TextField.GetDouble(jTextField_dtnxd_chieungang),
                    UTL_TextField.GetDouble(jTextField_dtnxd_chieungang1));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        if(!jTextField_dtnxd_chieudai.getText().equals("") && !jTextField_dtnxd_chieudai1.getText().equals(""))
        {
            re=new BLL_DTNXD().Filter_chieudai(re, UTL_TextField.GetDouble(jTextField_dtnxd_chieudai),
                    UTL_TextField.GetDouble(jTextField_dtnxd_chieudai1));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        if(!jTextField_dtnxd_dtkv.getText().equals("") && !jTextField_dtnxd_dtkv1.getText().equals(""))
        {
            re=new BLL_DTNXD().Filter_dtkv(re, UTL_TextField.GetDouble(jTextField_dtnxd_dtkv),
                    UTL_TextField.GetDouble(jTextField_dtnxd_dtkv1));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        if(!jTextField_dtnxd_dtxd.getText().equals("") && !jTextField_dtnxd_dtxd1.getText().equals(""))
        {
            re=new BLL_DTNXD().Filter_dtxd(re, UTL_TextField.GetDouble(jTextField_dtnxd_dtxd),
                    UTL_TextField.GetDouble(jTextField_dtnxd_dtxd1));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        if(!jTextField_dtnxd_dtsd.getText().equals("") && !jTextField_dtnxd_dtsd1.getText().equals(""))
        {
            re=new BLL_DTNXD().Filter_dtsd(re, UTL_TextField.GetDouble(jTextField_dtnxd_dtsd),
                    UTL_TextField.GetDouble(jTextField_dtnxd_dtsd1));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        if(!jTextField_dtnxd_dtsan.getText().equals("") && !jTextField_dtnxd_dtsan1.getText().equals(""))
        {
            re=new BLL_DTNXD().Filter_dtsan(re, UTL_TextField.GetDouble(jTextField_dtnxd_dtsan),
                    UTL_TextField.GetDouble(jTextField_dtnxd_dtsan1));
        }
        if(re.isEmpty())
        {
            Display_data(re);
            return;
        }
        if(jDateChooser_dtnxd_nxd.getDate()!=null && jDateChooser_dtnxd_nxd1.getDate()!=null)
        {
            re=new BLL_DTNXD().Filter_namxaydung(re, jDateChooser_dtnxd_nxd.getDate(), jDateChooser_dtnxd_nxd1.getDate());
        }
        
        //result
        Display_data(re);
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Load_pre_value();
        jButton_TimKiem.doClick();
        
        pack();
    }//GEN-LAST:event_formWindowOpened

    private void jButton_xemchitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xemchitietActionPerformed
        // TODO add your handling code here:
        ArrayList<ArrayList<Object>> rows = UTL_Table.GetTableSelectedRows(jTable_kq);
        int id= Integer.parseInt(String.valueOf(rows.get(0).get(0)));
        F_TTBDS vd=new F_TTBDS("xemchitiet", id);
        vd.setVisible(true);
        
    }//GEN-LAST:event_jButton_xemchitietActionPerformed

    private void jTable_kqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_kqMouseClicked
        // TODO add your handling code here:
        jButton_xemchitiet.setEnabled(jTable_kq.getSelectedRowCount()==1);
        jButton_sua.setEnabled(jTable_kq.getSelectedRowCount()==1);
        if(evt.getClickCount()==2)
        {
            jButton_sua.doClick();
        }
    }//GEN-LAST:event_jTable_kqMouseClicked

    private void jButton_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suaActionPerformed
        // TODO add your handling code here:
        String idd=String.valueOf(UTL_Table.GetTableSelectedRows(jTable_kq).get(0).get(0));
        int id= Integer.parseInt(idd);
        F_TTBDS vd=new F_TTBDS("sua", id);
        vd.setVisible(true);
    }//GEN-LAST:event_jButton_suaActionPerformed

    private void jButton_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xoaActionPerformed
        // TODO add your handling code here:
        ArrayList<ArrayList<Object>> re= UTL_Table.GetTableSelectedRows(jTable_kq);
        int opt = JOptionPane.showConfirmDialog(null, "Xóa "+re.size()+" phiếu TTBDS được chọn ?", "Xác nhận",
                                        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(opt==JOptionPane.YES_OPTION)
        {
            for(ArrayList<Object> row:re)
            {
                int ttbdsid = Integer.parseInt(String.valueOf(row.get(0)));
                new BLL_TTBDS().Xoa(ttbdsid);
            }
            jButton_TimKiem.doClick();
        }
    }//GEN-LAST:event_jButton_xoaActionPerformed

    private void jButton_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themActionPerformed
        // TODO add your handling code here:
        F_TTBDS vd=new F_TTBDS("them", 0);
        vd.setVisible(true);
    }//GEN-LAST:event_jButton_themActionPerformed
    private void Display_data(ArrayList<Integer> list)
    {
        //prepare table structure
        ArrayList<Object> col = new ArrayList<Object>();
        col.add("Mã phiếu");
        col.add("Ngày lập");
        col.add("Nhân viên lập");
        ArrayList<ArrayList<Object>> data = new ArrayList<ArrayList<Object>>();
        UTL_Table.SetTableData(jTable_kq, data, col, false);
        //add item to table
        for(Integer id:list)
        {
            DTO_TTBDS item = new BLL_TTBDS().Get(id);
            ArrayList<Object> row = new ArrayList<Object>();
            row.add(item.id);
            row.add(UTL_Date.ToStringValue(item.ngay,"dd/MM/yyyy"));
            row.add(item.fk_user.username+" ("+item.fk_user.fullname+")");
            UTL_Table.AddTableRow(jTable_kq, row);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_QLY_TTBDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_QLY_TTBDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_QLY_TTBDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_QLY_TTBDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_QLY_TTBDS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_sua;
    private javax.swing.JButton jButton_them;
    private javax.swing.JButton jButton_vt_chondc;
    private javax.swing.JButton jButton_xemchitiet;
    private javax.swing.JButton jButton_xoa;
    private javax.swing.JCheckBox jCheckBox_lbds_bietthu;
    private javax.swing.JCheckBox jCheckBox_lbds_canhochungcu;
    private javax.swing.JCheckBox jCheckBox_lbds_caoocvanphong;
    private javax.swing.JCheckBox jCheckBox_lbds_dat;
    private javax.swing.JCheckBox jCheckBox_lbds_matbang;
    private javax.swing.JCheckBox jCheckBox_lbds_nhapho;
    private javax.swing.JCheckBox jCheckBox_ttgd_ban;
    private javax.swing.JCheckBox jCheckBox_ttgd_chothue;
    private javax.swing.JCheckBox jCheckBox_ttgd_sangnhuong;
    private javax.swing.JCheckBox jCheckBox_ttgd_timmua;
    private javax.swing.JCheckBox jCheckBox_ttgd_timsang;
    private javax.swing.JCheckBox jCheckBox_ttgd_timthue;
    private javax.swing.JComboBox jComboBox_giagd_ban_donvi;
    private javax.swing.JComboBox jComboBox_giagd_ban_tiente;
    private javax.swing.JComboBox jComboBox_giagd_thue_donvi;
    private javax.swing.JComboBox jComboBox_giagd_thue_tiente;
    private javax.swing.JComboBox jComboBox_nhanvien;
    private javax.swing.JComboBox jComboBox_vt_huong;
    private com.toedter.calendar.JDateChooser jDateChooser_dtnxd_nxd;
    private com.toedter.calendar.JDateChooser jDateChooser_dtnxd_nxd1;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayfrom;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane_giagd;
    private javax.swing.JTable jTable_kq;
    private javax.swing.JTextField jTextField_dtnxd_chieudai;
    private javax.swing.JTextField jTextField_dtnxd_chieudai1;
    private javax.swing.JTextField jTextField_dtnxd_chieungang;
    private javax.swing.JTextField jTextField_dtnxd_chieungang1;
    private javax.swing.JTextField jTextField_dtnxd_dtkv;
    private javax.swing.JTextField jTextField_dtnxd_dtkv1;
    private javax.swing.JTextField jTextField_dtnxd_dtsan;
    private javax.swing.JTextField jTextField_dtnxd_dtsan1;
    private javax.swing.JTextField jTextField_dtnxd_dtsd;
    private javax.swing.JTextField jTextField_dtnxd_dtsd1;
    private javax.swing.JTextField jTextField_dtnxd_dtxd;
    private javax.swing.JTextField jTextField_dtnxd_dtxd1;
    private javax.swing.JTextField jTextField_giagd_ban;
    private javax.swing.JTextField jTextField_giagd_ban1;
    private javax.swing.JTextField jTextField_giagd_thue;
    private javax.swing.JTextField jTextField_giagd_thue1;
    private javax.swing.JTextField jTextField_ht_gac;
    private javax.swing.JTextField jTextField_ht_gac1;
    private javax.swing.JTextField jTextField_ht_solau;
    private javax.swing.JTextField jTextField_ht_solau1;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_lbds_khac;
    private javax.swing.JTextField jTextField_vt_diachi;
    // End of variables declaration//GEN-END:variables
}
